SONG_TYPES = (
    ("POP", "POP"),
    ("CLASSICAL", "CLASSICAL"),
    ("HIP_HOP", "HIP_HOP"),
    ("FOLK", "FOLK"),
    ("JAZZ", "JAZZ"),
)

PUBLIC = "PUBLIC"
PRIVATE = "PRIVATE"
COMMUNITY = "COMMUNITY"


PRIVACY = ((PUBLIC, "PUBLIC"), (PRIVATE, "PRIVATE"), (COMMUNITY, "COMMUNITY"))
