# Generated by Django 4.2.3 on 2023-07-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="privacy",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "PUBLIC"),
                    ("PRIVATE", "PRIVATE"),
                    ("COMMUNITY", "COMMUNITY"),
                ],
                default="PRIVATE",
                max_length=100,
            ),
        ),
    ]
