# Generated by Django 4.2.3 on 2023-07-05 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photo/"),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.CharField(
                choices=[
                    ("SINGER", "SINGER"),
                    ("WRITER", "WRITER"),
                    ("LISTENER", "LISTENER"),
                ],
                default="LISTENER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="enter a song name", max_length=200),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("cover_photo", models.ImageField(upload_to="cover_photo/")),
                (
                    "types",
                    models.CharField(
                        choices=[
                            ("POP", "POP"),
                            ("CLASSICAL", "CLASSICAL"),
                            ("HIP_HOP", "HIP_HOP"),
                            ("FOLK", "FOLK"),
                            ("JAZZ", "JAZZ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "singer",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sung_songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        max_length=200,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_songs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "owned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ManyToManyField(
                        related_name="playlist_song", to="user.song"
                    ),
                ),
            ],
        ),
    ]
