# Generated by Django 4.2.3 on 2023-07-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_name_user_profile_photo_user_roles_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
    ]
